<?php
/**
 * Tiny file-based store. Sensitive/runtime config is kept as PHP files that
 * `return` an array — safe to keep in the web root because fetching them over
 * HTTP executes PHP and yields no output.
 */

declare(strict_types=1);

/** Read an array from a "<?php return [...];" file. Returns [] if missing. */
function pb_read_array(string $path): array
{
    if (!is_file($path)) {
        return [];
    }
    $data = include $path;
    return is_array($data) ? $data : [];
}

/** Atomically write an array back to a "<?php return [...];" file. */
function pb_write_array(string $path, array $data): bool
{
    $dir = dirname($path);
    if (!is_dir($dir)) {
        @mkdir($dir, 0775, true);
    }
    $php = "<?php\n// Generated by the admin — do not edit while the app is running.\nreturn "
        . var_export($data, true) . ";\n";

    $tmp = $path . '.tmp' . bin2hex(random_bytes(4));
    if (file_put_contents($tmp, $php, LOCK_EX) === false) {
        return false;
    }
    @chmod($tmp, 0640);
    if (!rename($tmp, $path)) {
        @unlink($tmp);
        return false;
    }
    if (function_exists('opcache_invalidate')) {
        @opcache_invalidate($path, true);
    }
    return true;
}

// ---- Settings --------------------------------------------------------------
function pb_settings(): array
{
    $defaults = [
        'resend_api_key'   => '',
        'from_email'       => '',
        'from_name'        => 'Prague Boats Media',
        'reply_to'         => '',
        'bcc'              => 'mia@miladvorak.com',
        'media_url'        => '',
        'site_base_url'    => '',
        'subject_template' => 'Nové fotky – {boat}',
        'body_template'    => "Ahoj,\n\ndo lodi {boat} byly přidány nové fotky. Ukázky najdeš v příloze a níže v náhledu.\n\nDetail (konkrétní složka): {dropbox_link}\nMedia Hub: {media_url}\n\nHezký den!",
    ];
    return array_merge($defaults, pb_read_array(PB_CONFIG_DIR . '/settings.php'));
}

function pb_save_settings(array $settings): bool
{
    return pb_write_array(PB_CONFIG_DIR . '/settings.php', $settings);
}

// ---- Recipients ------------------------------------------------------------
/** @return array<int,array{email:string,name:string,active:bool}> */
function pb_recipients(): array
{
    $list = pb_read_array(PB_CONFIG_DIR . '/recipients.php');
    return array_values(array_filter($list, static fn($r) => is_array($r) && !empty($r['email'])));
}

function pb_save_recipients(array $list): bool
{
    return pb_write_array(PB_CONFIG_DIR . '/recipients.php', array_values($list));
}
